# Generated by Django 3.1.1 on 2020-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rete',
            field=models.IntegerField(default=0),
        ),
    ]
