# Generated by Django 3.1.1 on 2020-09-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_rete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rete',
            new_name='rate',
        ),
    ]
