# Generated by Django 3.0.8 on 2020-10-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='mess',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.AddField(
            model_name='contact',
            name='mob',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
